const LOGIN_LIMIT = 5;
const LOGIN_DURATION = 10 * 60;

const CHANGE_PASSWORD_LIMIT = 5;
const CHANGE_PASSWORD_DURATION = 10 * 60;

const FORGOT_PASSWORD_LIMIT = 5;
const FORGOT_PASSWORD_DURATION = 10 * 60;

const RESEND_OTP_LIMIT = 5;
const RESEND_OTP_DURATION = 10 * 60;

const REGISTER_LIMIT = 5;
const REGISTER_DURATION = 10 * 60;

const RESOURCE_LIMIT = 0;
const RESOURCE_REFILL_RATE_PER_SEC = 1 / 600;

const CONTRIBUTION_LIMIT = 0;
const CONTRIBUTION_REFILL_RATE_PER_SEC = 1 / 1200;

module.exports = {
  LOGIN_LIMIT,
  LOGIN_DURATION,
  CHANGE_PASSWORD_LIMIT,
  CHANGE_PASSWORD_DURATION,
  FORGOT_PASSWORD_LIMIT,
  FORGOT_PASSWORD_DURATION,
  RESEND_OTP_LIMIT,
  RESEND_OTP_DURATION,
  REGISTER_LIMIT,
  REGISTER_DURATION,
  RESOURCE_LIMIT,
  RESOURCE_REFILL_RATE_PER_SEC,
  CONTRIBUTION_LIMIT,
  CONTRIBUTION_REFILL_RATE_PER_SEC,
};