const STATUS_CODES = {
  // SUCCESS
  OK: 200,
  CREATED: 201,

  // CLIENT ERRORS
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUEST: 429,

  // SERVER ERRORS
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

module.exports = STATUS_CODES;
